apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: babludevops701/todo-list-image
      ports:
        - containerPort: 8081
